#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -N IsoQuant_Master
#PBS -m abe
#PBS -l nodes=1:ppn=2,mem=12gb
#PBS -o /data/gent/vo/000/gvo00082/vsc48905/Project/Preprocessing/Shimada/Nextflow/Output/Nextflow.stdout
#PBS -e /data/gent/vo/000/gvo00082/vsc48905/Project/Preprocessing/Shimada/Nextflow/Output/Nextflow.stderr

# Load Nextflow
module load Nextflow/25.10.2    

cd "${VSC_DATA_VO_USER}/Project/Preprocessing/Shimada/Nextflow/Output"

PROJECT_DIR="${VSC_DATA_VO_USER}/Nextflow/Pipeline_IsoQuant"

# Nextflow directories
export NXF_HOME="${VSC_DATA_VO_USER}/.nextflow"
export NXF_WORK="${VSC_SCRATCH_VO_USER}/nextflow_work"
export APPTAINER_CACHEDIR="${VSC_SCRATCH_VO_USER}/apptainer_cache"

mkdir -p $NXF_WORK $APPTAINER_CACHEDIR

# Java memory for Nextflow (fits inside 12GB PBS limit)
export NXF_OPTS="-Xms2g -Xmx8g"

# Run pipeline
nextflow run ${PROJECT_DIR}/main.nf \
    -profile cluster \
    --input "${VSC_DATA_VO_USER}/Project/Preprocessing/Shimada/Nextflow/Input/Shimada.csv" \
    --outdir results \
    --data_type 'pacbio_ccs' \
    --genome /data/gent/vo/000/gvo00082/vsc48905/Genomes/Genome/GRCh38.primary_assembly.genome.fa \
    --gtf /data/gent/vo/000/gvo00082/vsc48905/Genomes/Genome/gencode.v49.chr_patch_hapl_scaff.annotation.gtf \
    -resume \
    -with-trace trace.txt \
    -with-dag flowchart.png
