name: flexiplex_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flexiplex=1.01
  - numpy<2.0
  - pigz
  - gzip
  - pip:
      - git+https://github.com/DavidsonGroup/flexiplex.git#subdirectory=scripts