#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -N Nextflow_SC
#PBS -m abe
#PBS -l mem=12gb
#PBS -l nodes=1:ppn=8
#PBS -o /data/gent/vo/000/gvo00082/vsc48905/Project/Preprocessing/Zehra/Nextflow/Output/Nextflow.stdout
#PBS -e /data/gent/vo/000/gvo00082/vsc48905/Project/Preprocessing/Zehra/Nextflow/Output/Nextflow.stderr

# 1. Load Nextflow (Ensure version matches what you need)
module load Nextflow/25.10.2    

cd "${VSC_DATA_VO_USER}/Project/Preprocessing/Zehra/Nextflow/Output"  # adjust

# 2. Critical Paths (Use Scratch for heavy I/O)
PROJECT_DIR="${VSC_DATA_VO_USER}/Nextflow/Pipeline_IsoQuant_Single_cell"
export NXF_HOME="${VSC_DATA_VO_USER}/.nextflow"         # Keep config/history in DATA
export NXF_WORK="${VSC_SCRATCH_VO_USER}/nextflow_work"  # Keep temp files in SCRATCH
export APPTAINER_CACHEDIR="${VSC_SCRATCH_VO_USER}/apptainer_cache" # Images are big -> SCRATCH

# 3. Optimization Flags
# specific to Java/Nextflow memory usage on the head node
export NXF_OPTS="-Xms2g -Xmx8g"

mkdir -p $NXF_WORK $APPTAINER_CACHEDIR

# 4. Run the Pipeline
nextflow run ${PROJECT_DIR}/main.nf \
    -profile cluster \
    --input "${VSC_DATA_VO_USER}/Project/Preprocessing/Zehra/Nextflow/Input/Zehra.csv" \
    --outdir results \
    --data_type 'nanopore' \
    --sc_mode 'tenX_v3' \
    --barcode_tag 'CB' \
    --umi_tag 'UB' \
    --sc_platform 'ONT' \
    --sc_chemistry '10x3v2' \
    --genome /data/gent/vo/000/gvo00082/vsc48905/Genomes/Genome/GRCh38.primary_assembly.genome.fa \
    --gtf /data/gent/vo/000/gvo00082/vsc48905/Genomes/Genome/gencode.v49.chr_patch_hapl_scaff.annotation.gtf \
    -resume \
    -with-trace trace.txt \
    -with-dag flowchart.png \ 
