#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -N Nextflow_Sc
#PBS -m abe
#PBS -l mem=12gb
#PBS -l nodes=1:ppn=8
#PBS -o /data/gent/vo/000/gvo00082/vsc48905/Project/Preprocessing/Yang/Nextflow/Output/Nextflow.stdout
#PBS -e /data/gent/vo/000/gvo00082/vsc48905/Project/Preprocessing/Yang/Nextflow/Output/Nextflow.stderr

# 1. Load Nextflow (Ensure version matches what you need)
module load Nextflow/25.10.2
module load MultiQC/1.28-foss-2024a    

cd "${VSC_DATA_VO_USER}/Project/Preprocessing/Yang/Nextflow/Output"  # adjust


# 2. Critical Paths (Use Scratch for heavy I/O)
PROJECT_DIR="${VSC_DATA_VO_USER}/Nextflow/Pipeline_IsoQuant_Single_cell"
export NXF_HOME="${VSC_DATA_VO_USER}/.nextflow"         # Keep config/history in DATA
export NXF_WORK="${VSC_SCRATCH_VO_USER}/nextflow_work"  # Keep temp files in SCRATCH
export APPTAINER_CACHEDIR="${VSC_SCRATCH_VO_USER}/apptainer_cache" # Images are big -> SCRATCH

# 3. Optimization Flags
# specific to Java/Nextflow memory usage on the head node
export NXF_OPTS="-Xms2g -Xmx8g"

mkdir -p $NXF_WORK $APPTAINER_CACHEDIR

# 4. Run the Pipeline
nextflow run ${PROJECT_DIR}/main.nf \
    -profile cluster \
    --input "${VSC_DATA_VO_USER}/Project/Preprocessing/Yang/Nextflow/Input/Yang.csv" \
    --outdir results \
    --data_type 'pacbio_ccs' \
    --barcode_tag 'CB' \
    --umi_tag 'UB' \
    --sc_platform 'PACBIO' \
    --sc_chemistry '10x3v3' \
    --sc_mode 'tenX_v3' \
    --genome /data/gent/vo/000/gvo00082/vsc48905/Genomes/Genome/GRCh38.primary_assembly.genome.fa \
    --gtf /data/gent/vo/000/gvo00082/vsc48905/Genomes/Genome/gencode.v49.chr_patch_hapl_scaff.annotation.gtf \
    -resume \
    -with-report report.html \
    -with-trace trace.txt \
    -with-timeline timeline.html \
    -with-dag flowchart.png

# 3. THE FIX: Post-Processing MultiQC
# This only runs AFTER Nextflow has safely exited and closed all its files.
echo "Pipeline finished. Generating MultiQC report from results folder..."

multiqc results/ \
    -o '/data/gent/vo/000/gvo00082/vsc48905/Project/Preprocessing/Yang/Nextflow/Output/results/' \
    --filename "Yang_SingleCell_Project" \